Repository ereadingtool/ereadingtool, pull requests merged in 2020-11, with the labels that each got.

#241 Localize datetimes
  web/elm.json
  web/src/Pages/Text/Create.elm
  web/src/Pages/Text/Edit/Id_Int.elm
  web/src/Pages/Text/EditorSearch.elm
  web/src/Pages/Text/Search.elm
  web/src/Question/Decode.elm
  web/src/Question/Model.elm
  web/src/Shared.elm
  web/src/Text/Decode.elm
  web/src/Text/Model.elm
  web/src/Text/View.elm
  web/src/TextReader/Question/Decode.elm
  web/src/TextReader/Question/Model.elm
  web/src/TextReader/Text/Decode.elm
  web/src/TextReader/Text/Model.elm
  web/src/Utils/Date.elm
  web/tests/Tests/Date.elm
Labels: enhancement

#246 Add homepage and public nav items
  web/public/css/homepage.css
  web/public/img/reader-example.png
  web/src/Pages/Login/Student.elm
  web/src/Pages/Top.elm
  web/src/Shared.elm
  web/src/index.html
Labels: enhancement

#247 DELETE header added to cors configuration
  cors.conf
Labels: backend

#248 Upgrade password reset
  docker-compose.yml
  ereadingtool/settings.py
  user/templates/registration/password_reset_email.html
  user/test/student.py
  user/urls/forgot_pass.py
  user/urls/student.py
  user/views/api.py
  user/views/forgot_password.py
  user/views/instructor.py
  web/src/Pages/Signup/Instructor.elm
  web/src/Pages/User/ResetPassword/Uidb64_String/Token_String.elm
Labels: backend

#250 Make text search difficulty selection mutually exclusive
  web/src/Pages/Text/Search.elm
  web/src/Text/Search/Difficulty.elm
Labels: enhancement, text search

#251 Auth issue
  user/views/api.py
Labels: backend

#264 Change restart text button copy
  web/src/Pages/Text/Id_Int.elm
Labels: enhancement

#266 Make demo text easier to find
  web/public/css/text_search.css
  web/src/Pages/Text/Search.elm
Labels: enhancement, student, text search

#267 Small fixes to mobile navbar styles
  web/public/css/ereader.css
  web/src/Shared.elm
Labels: enhancement

#269 Update student difficulty preference from Shared
  web/src/Pages/Text/Search.elm
Labels: bug, student, text search

#274 Feature/optimize search
  text/models.py
  web/src/Pages/Text/Search.elm
  web/src/Text/Decode.elm
  web/src/Text/Model.elm
Labels: enhancement, text search

#236 Upgrade/jwt auth
  auth/normal_auth.py
  auth/producer_auth.py
  ereadingtool/settings.py
  ereadingtool/test/user.py
  ereadingtool/urls.py
  flashcards/tests.py
  flashcards/views.py
  instructor_admin/views.py
  mixins/view.py
  question/views.py
  report/migrations/0001_initial.py
  report/migrations/0002_student_performance_model.py
  text/consumers/base.py
  text/models.py
  text/tests.py
  text/translations/group/tests.py
  text/translations/tests.py
  text/views/api/lock.py
  text/views/api/tag.py
  text/views/api/text.py
  text/views/api/text_sections.py
  text/views/api/text_word/group.py
  text/views/api/text_word/word.py
  text/views/api/translations.py
  user/test/student.py
  user/urls/instructor.py
  user/urls/student.py
  user/views/api.py
  user/views/instructor.py
  user/views/mixin.py
  user/views/student.py
  user/views/student_performance.py
  user/views/username.py
Labels: accounts, backend

#276 Optimize search cleanup
  web/src/User/Instructor/Profile.elm
Labels: bug, instructor

#277 Add expired token handling to the frontend
  web/package-lock.json
  web/package.json
  web/public/css/ereader.css
  web/src/Infobar.elm
  web/src/Pages/Profile/Instructor.elm
  web/src/Pages/Profile/Student.elm
  web/src/Pages/Text/Create.elm
  web/src/Pages/Text/Edit/Id_Int.elm
  web/src/Pages/Text/Search.elm
  web/src/Shared.elm
  web/src/index.ts
Labels: accounts, enhancement

#278 Feature/redis env setting
  docker-compose.yml
  ereadingtool/settings.py
Labels: CI

#279 Fix hidden navbar overhang
  web/public/css/ereader.css
Labels: bug
