Repository ereadingtool/ereadingtool, pull requests merged in 2020-12, with the labels that each got.

#283 New branch
  Dockerfile.django
  Dockerfile.node
Labels: CI

#287 Change read again to a link and take id from page
  web/src/Pages/Text/Id_Int.elm
Labels: bug

#289 Add lemmas
  web/src/Pages/Text/Id_Int.elm
  web/src/Text/Translations.elm
  web/src/Text/Translations/Model.elm
  web/src/Text/Translations/View.elm
  web/src/Text/Translations/Word/Instance.elm
  web/src/TextReader/TextWord.elm
Labels: enhancement, glossing

#295 Add pointer on hover over logout link
  web/src/Shared.elm
Labels: styling

#296 Fix forgot password submit button styling
  web/src/Pages/User/ForgotPassword.elm
Labels: styling

#297 Text search fixes
  web/src/InstructorAdmin/Admin/Text.elm
  web/src/Pages/Text/Search.elm
  web/src/Text/Search.elm
  web/src/Text/Translations/Update.elm
Labels: bug, text search
