Repository ereadingtool/ereadingtool, pull requests merged in 2021-03, with the labels that each got.

#361 Rename instructor to content creator
  web/src/Pages/Login/ContentCreator.elm
  web/src/Pages/Login/Student.elm
  web/src/Pages/NotFound.elm
  web/src/Pages/Profile/ContentCreator.elm
  web/src/Pages/Signup/ContentCreator.elm
  web/src/Pages/Text/Create.elm
  web/src/Pages/Text/CreatorSearch.elm
  web/src/Pages/Text/Edit/Id_Int.elm
  web/src/Shared.elm
  web/src/Spa/Page.elm
Labels: enhancement, instructor

#327 Bugfix/text search filters
  report/models.py
  text/views/api/text.py
  web/src/Text/Search/ReadingStatus.elm
Labels: backend, bug, text search

#372 Feature/remove debug stmts
  Dockerfile.node
  web/src/Pages/Flashcards/Student.elm
  web/src/Pages/Text/Id_Int.elm
  web/src/Text/Component.elm
  web/src/Text/Translations/Update.elm
Labels: enhancement

#371 Feature/enable gzip
  Dockerfile.node
  nginx.conf
Labels: enhancement

#370 Difficulty styling
  text/ui/TextSearch.elm
  web/src/Pages/Text/Search.elm
Labels: styling, text search

#373 Updating endpoints
  web/.env.devel
  web/.env.production
Labels: bug

#374 Opacity bugfix
  web/public/css/homepage.css
Labels: styling

#377 EB Garamond for titles, Open Sans for bodies
  web/public/css/create_text.css
  web/public/css/ereader.css
  web/public/css/hint-down-left.css
  web/public/css/hint-down-right.css
  web/public/css/hint-up-left.css
  web/public/css/hint-up-right.css
  web/public/css/homepage.css
  web/public/css/text.css
  web/public/css/text_search.css
  web/public/css/user.css
  web/public/css/user_profile.css
  web/public/fonts/eb-garamond-bold.woff2
  web/public/fonts/eb-garamond-italic.woff2
  web/public/fonts/eb-garamond-regular.woff2
  web/public/fonts/fonts/eb-garamond-bold.woff2
  web/public/fonts/fonts/eb-garamond-italic.woff2
  web/public/fonts/fonts/eb-garamond-regular.woff2
  web/public/fonts/fonts/opensans-bold.woff2
  web/public/fonts/fonts/opensans-italic.woff2
  web/public/fonts/fonts/opensans-regular.woff2
  web/public/fonts/opensans-bold.woff2
  web/public/fonts/opensans-italic.woff2
  web/public/fonts/opensans-regular.woff2
Labels: styling

#380 Changes to CSS
  web/public/css/create_text.css
  web/public/css/ereader-unauth.css
  web/public/css/ereader.css
  web/public/css/error.css
  web/public/css/hint.css
  web/public/css/instructor_profile.css
  web/public/css/text.css
  web/public/css/text_search.css
  web/public/css/user.css
  web/public/css/user_reset_pass.css
  web/src/Pages/Text/CreatorSearch.elm
  web/src/Pages/Text/Edit/Id_Int.elm
  web/src/User/Login.elm
  web/src/index.html
Labels: styling

#386 Navbar font size increase
  web/public/css/ereader.css
Labels: styling

#393 Signup page contents
  web/public/css/ereader.css
  web/src/Pages/Signup/Student.elm
Labels: styling

#395 Feature/mobile styling
  web/public/css/ereader.css
  web/public/css/user_profile.css
  web/src/Pages/Profile/Student.elm
Labels: styling

#398 Student Profile Page Styling Enhancements
  web/package-lock.json
  web/public/css/ereader.css
  web/public/css/user.css
  web/public/css/user_profile.css
  web/public/img/check_box.svg
  web/public/img/check_box_outline.svg
  web/src/Pages/Profile/Student.elm
Labels: styling
