Repository ereadingtool/ereadingtool, pull requests merged in 2021-01, with the labels that each got.

#300 Feature/update word tagging
  web/elm.json
  web/public/css/ereader.css
  web/src/Pages/Text/Id_Int.elm
  web/src/Text/Section/Words/Tag.elm
  web/src/Text/Translations/Model.elm
  web/src/Text/Translations/View.elm
  web/src/TextReader/Section/Model.elm
  web/src/TextReader/TextWord.elm
  web/src/TextReader/View.elm
  web/tests/TagSection/Reader.elm
  web/tests/Word/Tests.elm
Labels: enhancement, glossing

#307 Feature/instructor invite styling
  web/public/css/instructor_profile.css
  web/src/Pages/Profile/Instructor.elm
  web/src/User/Instructor/Invite.elm
  web/src/User/Instructor/Invite/Decode.elm
  web/src/User/Instructor/Profile.elm
Labels: styling

#305 Feature/update homepage links
  web/public/css/ereader.css
  web/src/User/Login.elm
Labels: styling

#308 Feature/styling links
  text/static/text/css/text_search.css
  web/public/css/instructor_profile.css
  web/public/css/text_search.css
  web/public/css/user.css
  web/public/css/user_profile.css
Labels: styling

#309 instructor -> content editor
  user/ui/Instructor/Profile/View.elm
  web/src/Pages/Profile/Instructor.elm
  web/src/User/Instructor/Profile/View.elm
Labels: styling

#311 Feature/first time correct
  ereadingtool/settings.py
  first_time_correct/__init__.py
  first_time_correct/admin.py
  first_time_correct/apps.py
  first_time_correct/migrations/0001_initial.py
  first_time_correct/migrations/0002_auto_20201218_1931.py
  first_time_correct/migrations/0003_auto_20210113_1855.py
  first_time_correct/migrations/__init__.py
  first_time_correct/models.py
  first_time_correct/tests.py
  first_time_correct/views.py
  report/migrations/0002_auto_20210113_1855.py
  report/models.py
  report/templates/student_performance_report.html
  text/consumers/base.py
  web/public/css/user_profile.css
  web/src/Api/Endpoint.elm
  web/src/Pages/Profile/Student.elm
  web/src/User/Student/Performance/Report.elm
Labels: enhancement

#315 Feature/styling public pages
  instructor_admin/static/admin/css/create_text.css
  user/static/css/user.css
  user/static/css/user_profile.css
  user/ui/Student/Student_Signup.elm
  web/public/css/create_text.css
  web/public/css/ereader.css
  web/public/css/user.css
  web/public/css/user_profile.css
  web/public/img/visibility-24px.svg
  web/public/img/visibility_off-24px.svg
  web/src/Pages/Login/Instructor.elm
  web/src/Pages/Signup/Student.elm
  web/src/User/Login.elm
  web/src/User/SignUp.elm
  web/src/index.html
Labels: styling

#319 Add left and right double quotation marks
  web/src/Text/Section/Words/Tag.elm
Labels: bug

#316 Add favicon
  web/public/img/favicons/android-chrome-192x192.png
  web/public/img/favicons/android-chrome-512x512.png
  web/public/img/favicons/apple-touch-icon.png
  web/public/img/favicons/favicon-16x16.png
  web/public/img/favicons/favicon-32x32.png
  web/public/img/favicons/favicon.ico
  web/src/index.html
Labels: enhancement

#320 Add ids to email and password inputs
  web/src/User/Login.elm
Labels: bug

#322 Update student profile on profile page init
  web/src/Pages/Profile/Student.elm
Labels: accounts, student

#324 Feature/ci cd with actions
  .circleci/config.yml
  .github/workflows/tests.yml
  ereadingtool/test/user.py
  text/tests.py
  text/translations/group/tests.py
  text/translations/tests.py
Labels: CI

#334 Hint box restyled
  web/public/css/ereader.css
  web/public/css/hint-down-left.css
  web/public/css/hint-down-right.css
  web/public/css/hint-up-left.css
  web/public/css/hint-up-right.css
Labels: styling

#328 Stylized input boxes
  user/ui/ForgotPassword/Forgot_Password.elm
  web/public/css/ereader.css
  web/src/Pages/Signup/Instructor.elm
  web/src/Pages/User/ForgotPassword.elm
  web/src/Pages/User/ResetPassword/Uidb64_String/Token_String.elm
  web/src/User/Login.elm
  web/src/User/SignUp.elm
Labels: styling

#335 Add em dash (U+2014) as trailing punctuation
  web/src/Text/Section/Words/Tag.elm
  web/tests/Word/Tests.elm
Labels: enhancement, glossing

#336 Fix text search tag styling
  web/public/css/ereader.css
Labels: bug
